executor: LocalExecutor

postgresql:
  enabled: true

  image:
    registry: docker.io
    repository: bitnamilegacy/postgresql
    tag: 16.1.0-debian-11-r15
    pullPolicy: IfNotPresent

  auth:
    enablePostgresUser: true
    postgresPassword: postgres
    username: airflow
    password: airflow
    database: airflow

  primary:
    persistence:
      enabled: false

redis:
  enabled: false

dags:
  persistence:
    enabled: false

  gitSync:
    enabled: true
    repo: "https://github.com/parkjoohyung0826/Airflow-on-k8s-Q4.git"
    branch: "main"
    rev: "HEAD"
    depth: 1
    subPath: "airflow-dags"
    wait: 60
    maxFailures: 0


logs:
  persistence:
    enabled: False

config:
  core:
    load_examples: "False"

webserver:
  service:
    type: ClusterIP